notifications:
  email: false

# Quick boot options
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure:

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - sudo apt-get install alsa-base alsa-utils
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
node_js:
  - '0'
  - 4
  - 5
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint
addons:
  apt:
    packages:
      - xvfb

# Npm publish options (see https://gist.github.com/59naga/42278a7c9702411f506f)
# before_deploy:
#   - npm run build
# deploy:
#   skip_cleanup: true # keep the devDependencies
#   provider: npm
#   email: i59naga@icloud.com
#   api_key:
#     secure:
#   on:
#     node: 4
