# refs
# http://qiita.com/pine613/items/b1b0ec71b959f639fa38
# https://github.com/nodejs/nan/blob/master/appveyor.yml
#
build: off
deploy: off
os: unstable

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "3"
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run cover
  - npm run lint
